apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: api
spec:
  type: ClusterIP  # Internal cluster access only
  ports:
    - port: 8000        # Service port
      targetPort: 8000  # Container port
      protocol: TCP
      name: http
  selector:
    app: api  # Matches the labels from the deployment pods
